# Base16 Katy - alacritty color config
# George Essig (https://github.com/gessig)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x292d3e'
foreground = '0x959dcb'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x292d3e'
cursor = '0x959dcb'

# Normal colors
[colors.normal]
black = '0x292d3e'
red = '0x6e98e1'
green = '0x78c06e'
yellow = '0xe0a557'
blue = '0x82aaff'
magenta = '0xc792ea'
cyan = '0x83b7e5'
white = '0x959dcb'

# Bright colors
[colors.bright]
black = '0x676e95'
red = '0xf78c6c'
green = '0x444267'
yellow = '0x5c598b'
blue = '0x8796b0'
magenta = '0x959dcb'
cyan = '0xff5370'
white = '0xffffff'
