# Base16 Github 256 - alacritty color config
# Defman21

# Default colors
[colors.primary]
background = '0xffffff'
foreground = '0x333333'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xffffff'
cursor = '0x333333'

# Normal colors
[colors.normal]
black = '0xffffff'
red = '0xed6a43'
green = '0x183691'
yellow = '0x795da3'
blue = '0x795da3'
magenta = '0xa71d5d'
cyan = '0x183691'
white = '0x333333'

# Bright colors
[colors.bright]
black = '0x969896'
red = '0xed6a43'
green = '0x183691'
yellow = '0x795da3'
blue = '0x795da3'
magenta = '0xa71d5d'
cyan = '0x183691'
white = '0xffffff'

[[colors.indexed_colors]]
index = 16
color = "0x0086b3"

[[colors.indexed_colors]]
index = 17
color = "0x333333"

[[colors.indexed_colors]]
index = 18
color = "0xf5f5f5"

[[colors.indexed_colors]]
index = 19
color = "0xc8c8fa"

[[colors.indexed_colors]]
index = 20
color = "0xe8e8e8"

[[colors.indexed_colors]]
index = 21
color = "0xffffff"
