# Base16 caroline - alacritty color config
# ed (https://codeberg.org/ed)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1c1213'
foreground = '0xa87569'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1c1213'
cursor = '0xa87569'

# Normal colors
[colors.normal]
black = '0x1c1213'
red = '0xc24f57'
green = '0x806c61'
yellow = '0xf28171'
blue = '0x684c59'
magenta = '0xa63650'
cyan = '0x6b6566'
white = '0xa87569'

# Bright colors
[colors.bright]
black = '0x6d4745'
red = '0xa63650'
green = '0x3a2425'
yellow = '0x563837'
blue = '0x8b5d57'
magenta = '0xc58d7b'
cyan = '0x893f45'
white = '0xe3a68c'
