# Base16 Primer Dark - alacritty color config
# Jimmy Lin

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x010409'
foreground = '0xb1bac4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x010409'
cursor = '0xb1bac4'

# Normal colors
[colors.normal]
black = '0x010409'
red = '0xff7b72'
green = '0x3fb950'
yellow = '0xd29922'
blue = '0x58a6ff'
magenta = '0xf778ba'
cyan = '0xa5d6ff'
white = '0xb1bac4'

# Bright colors
[colors.bright]
black = '0x484f58'
red = '0xf0883e'
green = '0x21262d'
yellow = '0x30363d'
blue = '0x8b949e'
magenta = '0xc9d1d9'
cyan = '0xbd561d'
white = '0xf0f6fc'
