# Base16 Kanagawa - alacritty color config
# Tommaso Laurenzi (https://github.com/rebelot)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1f1f28'
foreground = '0xdcd7ba'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1f1f28'
cursor = '0xdcd7ba'

# Normal colors
[colors.normal]
black = '0x1f1f28'
red = '0xc34043'
green = '0x76946a'
yellow = '0xc0a36e'
blue = '0x7e9cd8'
magenta = '0x957fb8'
cyan = '0x6a9589'
white = '0xdcd7ba'

# Bright colors
[colors.bright]
black = '0x54546d'
red = '0xffa066'
green = '0x16161d'
yellow = '0x223249'
blue = '0x727169'
magenta = '0xc8c093'
cyan = '0xd27e99'
white = '0x717c7c'
