# Base16 vice - alacritty color config
# Thomas Leon Highbaugh thighbaugh@zoho.com

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x17191e'
foreground = '0x8b9cbe'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x17191e'
cursor = '0x8b9cbe'

# Normal colors
[colors.normal]
black = '0x17191e'
red = '0xff29a8'
green = '0x0badff'
yellow = '0xf0ffaa'
blue = '0x00eaff'
magenta = '0x00f6d9'
cyan = '0x8265ff'
white = '0x8b9cbe'

# Bright colors
[colors.bright]
black = '0x383a47'
red = '0x85ffe0'
green = '0x22262d'
yellow = '0x3c3f4c'
blue = '0x555e70'
magenta = '0xb2bfd9'
cyan = '0xff3d81'
white = '0xf4f4f7'
