# Base16 emil - alacritty color config
# limelier

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xefefef'
foreground = '0x313145'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xefefef'
cursor = '0x313145'

# Normal colors
[colors.normal]
black = '0xefefef'
red = '0xf43979'
green = '0x0073a8'
yellow = '0xff669b'
blue = '0x471397'
magenta = '0x6916b6'
cyan = '0x2155d6'
white = '0x313145'

# Bright colors
[colors.bright]
black = '0x7c7c98'
red = '0xd22a8b'
green = '0xbebed2'
yellow = '0x9e9eaf'
blue = '0x505063'
magenta = '0x22223a'
cyan = '0x8d17a5'
white = '0x1a1a2f'
