# Base16 tarot - alacritty color config
# ed (https://codeberg.org/ed)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x0e091d'
foreground = '0xaa556f'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0e091d'
cursor = '0xaa556f'

# Normal colors
[colors.normal]
black = '0x0e091d'
red = '0xc53253'
green = '0xa68e5a'
yellow = '0xff6565'
blue = '0x6e6080'
magenta = '0xa45782'
cyan = '0x8c9785'
white = '0xaa556f'

# Bright colors
[colors.bright]
black = '0x74316b'
red = '0xea4d60'
green = '0x2a153c'
yellow = '0x4b2054'
blue = '0x8c406f'
magenta = '0xc4686d'
cyan = '0x984d51'
white = '0xdc8f7c'
