# Base16 Synth Midnight Terminal Dark - alacritty color config
# MichaÃ«l Ball (http://github.com/michael-ball/)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x050608'
foreground = '0xc1c3c4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x050608'
cursor = '0xc1c3c4'

# Normal colors
[colors.normal]
black = '0x050608'
red = '0xb53b50'
green = '0x06ea61'
yellow = '0xc9d364'
blue = '0x03aeff'
magenta = '0xea5ce2'
cyan = '0x42fff9'
white = '0xc1c3c4'

# Bright colors
[colors.bright]
black = '0x474849'
red = '0xea770d'
green = '0x1a1b1c'
yellow = '0x28292a'
blue = '0xa3a5a6'
magenta = '0xcfd1d2'
cyan = '0xcd6320'
white = '0xdddfe0'
