# Base16 Blueish - alacritty color config
# Ben Mayoras

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x182430'
foreground = '0xc8e1f8'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x182430'
cursor = '0xc8e1f8'

# Normal colors
[colors.normal]
black = '0x182430'
red = '0x4ce587'
green = '0xc3e88d'
yellow = '0x82aaff'
blue = '0x82aaff'
magenta = '0xff84dd'
cyan = '0x5fd1ff'
white = '0xc8e1f8'

# Bright colors
[colors.bright]
black = '0x616d78'
red = '0xf6a85c'
green = '0x243c54'
yellow = '0x46290a'
blue = '0x74afe7'
magenta = '0xddeaf6'
cyan = '0xbbd2e8'
white = '0x8f98a0'
