# Base16 lime - alacritty color config
# limelier

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1a1a2f'
foreground = '0x818175'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1a1a2f'
cursor = '0x818175'

# Normal colors
[colors.normal]
black = '0x1a1a2f'
red = '0xff662a'
green = '0x8cd97c'
yellow = '0xffd15e'
blue = '0x2b926f'
magenta = '0x1b825f'
cyan = '0x4cad83'
white = '0x818175'

# Bright colors
[colors.bright]
black = '0x313140'
red = '0xff773a'
green = '0x202030'
yellow = '0x2a2a3f'
blue = '0x515155'
magenta = '0xfff2d1'
cyan = '0xb4d97c'
white = '0xfff8e1'
