# Base16 selenized-black - alacritty color config
# Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x181818'
foreground = '0xb9b9b9'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x181818'
cursor = '0xb9b9b9'

# Normal colors
[colors.normal]
black = '0x181818'
red = '0xed4a46'
green = '0x70b433'
yellow = '0xdbb32d'
blue = '0x368aeb'
magenta = '0xa580e2'
cyan = '0x3fc5b7'
white = '0xb9b9b9'

# Bright colors
[colors.bright]
black = '0x777777'
red = '0xe67f43'
green = '0x252525'
yellow = '0x3b3b3b'
blue = '0x777777'
magenta = '0xdedede'
cyan = '0xeb6eb7'
white = '0xdedede'
