# Base16 selenized-dark - alacritty color config
# Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x103c48'
foreground = '0xadbcbc'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x103c48'
cursor = '0xadbcbc'

# Normal colors
[colors.normal]
black = '0x103c48'
red = '0xfa5750'
green = '0x75b938'
yellow = '0xdbb32d'
blue = '0x4695f7'
magenta = '0xaf88eb'
cyan = '0x41c7b9'
white = '0xadbcbc'

# Bright colors
[colors.bright]
black = '0x72898f'
red = '0xed8649'
green = '0x184956'
yellow = '0x2d5b69'
blue = '0x72898f'
magenta = '0xcad8d9'
cyan = '0xf275be'
white = '0xcad8d9'
