# Base16 Catppuccin Mocha - alacritty color config
# https://github.com/catppuccin/catppuccin

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1e1e2e'
foreground = '0xcdd6f4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1e1e2e'
cursor = '0xcdd6f4'

# Normal colors
[colors.normal]
black = '0x1e1e2e'
red = '0xf38ba8'
green = '0xa6e3a1'
yellow = '0xf9e2af'
blue = '0x89b4fa'
magenta = '0xcba6f7'
cyan = '0x94e2d5'
white = '0xcdd6f4'

# Bright colors
[colors.bright]
black = '0x45475a'
red = '0xfab387'
green = '0x181825'
yellow = '0x313244'
blue = '0x585b70'
magenta = '0xf5e0dc'
cyan = '0xf2cdcd'
white = '0xb4befe'
