# Base16 standardized-dark - alacritty color config
# ali (https://github.com/ali-githb/base16-standardized-scheme)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x222222'
foreground = '0xc0c0c0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x222222'
cursor = '0xc0c0c0'

# Normal colors
[colors.normal]
black = '0x222222'
red = '0xe15d67'
green = '0x5db129'
yellow = '0xe1b31a'
blue = '0x00a3f2'
magenta = '0xb46ee0'
cyan = '0x21c992'
white = '0xc0c0c0'

# Bright colors
[colors.bright]
black = '0x898989'
red = '0xfc804e'
green = '0x303030'
yellow = '0x555555'
blue = '0x898989'
magenta = '0xe0e0e0'
cyan = '0xb87d28'
white = '0xffffff'
