# Base16 Ayu Dark - alacritty color config
# Khue Nguyen &lt;Z5483Y@gmail.com&gt;

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x0f1419'
foreground = '0xe6e1cf'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0f1419'
cursor = '0xe6e1cf'

# Normal colors
[colors.normal]
black = '0x0f1419'
red = '0xf07178'
green = '0xb8cc52'
yellow = '0xffb454'
blue = '0x59c2ff'
magenta = '0xd2a6ff'
cyan = '0x95e6cb'
white = '0xe6e1cf'

# Bright colors
[colors.bright]
black = '0x3e4b59'
red = '0xff8f40'
green = '0x131721'
yellow = '0x272d38'
blue = '0xbfbdb6'
magenta = '0xe6e1cf'
cyan = '0xe6b673'
white = '0xf3f4f5'
