# Base16 Gruvbox Material Light, Soft - alacritty color config
# Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xf2e5bc'
foreground = '0x654735'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xf2e5bc'
cursor = '0x654735'

# Normal colors
[colors.normal]
black = '0xf2e5bc'
red = '0xc14a4a'
green = '0x6c782e'
yellow = '0xb47109'
blue = '0x45707a'
magenta = '0x945e80'
cyan = '0x4c7a5d'
white = '0x654735'

# Bright colors
[colors.bright]
black = '0xa89984'
red = '0xc35e0a'
green = '0xebdbb2'
yellow = '0xc9b99a'
blue = '0x665c54'
magenta = '0x3c3836'
cyan = '0xe78a4e'
white = '0x282828'
