# Base16 pandora - alacritty color config
# Cassandra Fox

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x131213'
foreground = '0xf15c99'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x131213'
cursor = '0xf15c99'

# Normal colors
[colors.normal]
black = '0x131213'
red = '0xb00b69'
green = '0x9ddf69'
yellow = '0xffcc00'
blue = '0x008080'
magenta = '0xa24030'
cyan = '0x714ca6'
white = '0xf15c99'

# Bright colors
[colors.bright]
black = '0xffbee3'
red = '0xff9153'
green = '0x2f1823'
yellow = '0x472234'
blue = '0x9b2a46'
magenta = '0x81506a'
cyan = '0xa24030'
white = '0x632227'
