# Base16 Oxocarbon Light - alacritty color config
# shaunsingh/IBM

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xf2f4f8'
foreground = '0x393939'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xf2f4f8'
cursor = '0x393939'

# Normal colors
[colors.normal]
black = '0xf2f4f8'
red = '0xff7eb6'
green = '0x0f62fe'
yellow = '0xff6f00'
blue = '0x42be65'
magenta = '0xbe95ff'
cyan = '0x673ab7'
white = '0x393939'

# Bright colors
[colors.bright]
black = '0x161616'
red = '0xee5396'
green = '0xdde1e6'
yellow = '0x525252'
blue = '0x262626'
magenta = '0x525252'
cyan = '0x37474f'
white = '0x08bdba'
