# Base16 Spaceduck - alacritty color config
# Guillermo Rodriguez (https://github.com/pineapplegiant), packaged by Gabriel Fontes (https://github.com/Misterio77)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x16172d'
foreground = '0xecf0c1'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x16172d'
cursor = '0xecf0c1'

# Normal colors
[colors.normal]
black = '0x16172d'
red = '0xe33400'
green = '0x5ccc96'
yellow = '0xf2ce00'
blue = '0x7a5ccc'
magenta = '0xb3a1e6'
cyan = '0x00a3cc'
white = '0xecf0c1'

# Bright colors
[colors.bright]
black = '0x686f9a'
red = '0xe39400'
green = '0x1b1c36'
yellow = '0x30365f'
blue = '0x818596'
magenta = '0xc1c3cc'
cyan = '0xce6f8f'
white = '0xffffff'
