# Base16 Stella - alacritty color config
# Shrimpram

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x2b213c'
foreground = '0x998bad'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2b213c'
cursor = '0x998bad'

# Normal colors
[colors.normal]
black = '0x2b213c'
red = '0xc79987'
green = '0xacc79b'
yellow = '0xc7c691'
blue = '0xa5aad4'
magenta = '0xc594ff'
cyan = '0x9bc7bf'
white = '0x998bad'

# Bright colors
[colors.bright]
black = '0x655978'
red = '0x8865c6'
green = '0x362b48'
yellow = '0x4d4160'
blue = '0x7f7192'
magenta = '0xb4a5c8'
cyan = '0xc7ab87'
white = '0xebdcff'
