# Base16 Jabuti - alacritty color config
# https://github.com/notusknot

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x292a37'
foreground = '0xc0cbe3'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x292a37'
cursor = '0xc0cbe3'

# Normal colors
[colors.normal]
black = '0x292a37'
red = '0xec6a88'
green = '0x3fdaa4'
yellow = '0xe1c697'
blue = '0x3fc6de'
magenta = '0xbe95ff'
cyan = '0xff7eb6'
white = '0xc0cbe3'

# Bright colors
[colors.bright]
black = '0x45475d'
red = '0xefb993'
green = '0x343545'
yellow = '0x3c3e51'
blue = '0x50526b'
magenta = '0xd9e0ee'
cyan = '0x8b8da9'
white = '0xffffff'
